// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASG8mxXgaHKEIoiaqLlIQ9taEKCPSzk8',
    appId: '1:626328647115:web:8d6e79853c2d45c8c9f24e',
    messagingSenderId: '626328647115',
    projectId: 'flutter-crud-firebase-b60fe',
    authDomain: 'flutter-crud-firebase-b60fe.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-b60fe.firebasestorage.app',
    measurementId: 'G-QWB5H67Y4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnDoLhqI_2UDx81xoP_tzOxqjW8dJ7R9c',
    appId: '1:626328647115:android:e78a46ee17d71c04c9f24e',
    messagingSenderId: '626328647115',
    projectId: 'flutter-crud-firebase-b60fe',
    storageBucket: 'flutter-crud-firebase-b60fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzaeMPOCVHqdVOwEfhspSU45srNub0ZS0',
    appId: '1:626328647115:ios:db0f814f214cd153c9f24e',
    messagingSenderId: '626328647115',
    projectId: 'flutter-crud-firebase-b60fe',
    storageBucket: 'flutter-crud-firebase-b60fe.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiandroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzaeMPOCVHqdVOwEfhspSU45srNub0ZS0',
    appId: '1:626328647115:ios:db0f814f214cd153c9f24e',
    messagingSenderId: '626328647115',
    projectId: 'flutter-crud-firebase-b60fe',
    storageBucket: 'flutter-crud-firebase-b60fe.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiandroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAASG8mxXgaHKEIoiaqLlIQ9taEKCPSzk8',
    appId: '1:626328647115:web:c5057900a491d516c9f24e',
    messagingSenderId: '626328647115',
    projectId: 'flutter-crud-firebase-b60fe',
    authDomain: 'flutter-crud-firebase-b60fe.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-b60fe.firebasestorage.app',
    measurementId: 'G-XCL1NL4NYC',
  );
}
