// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApr9ZrDiXG4kL1zO4CaIPb3JWYWH8Kqp4',
    appId: '1:10599806440:web:a5afec8595a67ee237605d',
    messagingSenderId: '10599806440',
    projectId: 'waja-85cf8',
    authDomain: 'waja-85cf8.firebaseapp.com',
    storageBucket: 'waja-85cf8.firebasestorage.app',
    measurementId: 'G-0TD8BEBG7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXNad9cqB-8JKjcblTY_RayWVI_apPSyg',
    appId: '1:10599806440:android:ca04ec9e1aed249d37605d',
    messagingSenderId: '10599806440',
    projectId: 'waja-85cf8',
    storageBucket: 'waja-85cf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXMVwsoq5ttBzsF43xsiAzcyMlBDfa50Q',
    appId: '1:10599806440:ios:c7cf06f4c4d98e6d37605d',
    messagingSenderId: '10599806440',
    projectId: 'waja-85cf8',
    storageBucket: 'waja-85cf8.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiandroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXMVwsoq5ttBzsF43xsiAzcyMlBDfa50Q',
    appId: '1:10599806440:ios:c7cf06f4c4d98e6d37605d',
    messagingSenderId: '10599806440',
    projectId: 'waja-85cf8',
    storageBucket: 'waja-85cf8.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiandroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApr9ZrDiXG4kL1zO4CaIPb3JWYWH8Kqp4',
    appId: '1:10599806440:web:16854a3c9c4322d037605d',
    messagingSenderId: '10599806440',
    projectId: 'waja-85cf8',
    authDomain: 'waja-85cf8.firebaseapp.com',
    storageBucket: 'waja-85cf8.firebasestorage.app',
    measurementId: 'G-CR35YV6XXL',
  );

}